1. Viết lại hàm tách dữ liệu thành tập Train và tập Test

In [315]:
import numpy as np
import pandas as pd

In [316]:
def train_test_split(dataset, test_Number):
  import random
  import numpy as np
    #khởi tạo tập test rỗng
  test_data= []
    #lấy từng hàng ở tập dataset đưa vào tập test
  while len(test_data) < test_Number:
        #lấy index ngẫu nhiên trong tập tập dữ liệu
      index = random.randrange(len(dataset))
        #đưa hàng thứ index vào tập test đồng thời xóa ở dataset
        #chuyển dataset qua list để dùng hàm pop. Hàm này dùng để xóa hàng
      test_data.append(list(dataset).pop(index))
  temp=test_data
  y_test=np.array(temp)[:,-1]
    #y_test=X_test[:,-1]
   # X_test1=X_test[:,:-1]
  return dataset,test_data,y_test

2. Viết hàm tính kỳ vòng. Kỳ vòng được tính bằng 1/n*sum(xi)

In [317]:
def mean(numbers):
    if len(numbers) == 0:
        return 0
    return sum(numbers) / float(len(numbers))

3. Viết hàm tính phương sai. Phương sai được tính bằng căn bậc hai của:
# 1/(n-1)*sum(bình phương(xi-kỳ vọng))

In [318]:
import math
def standard_deviation(numbers):
    if len(numbers) < 2:
        return 0
    avg = mean(numbers)
    variance = sum([(x - avg)**2 for x in numbers]) / float(len(numbers) - 1)
    return math.sqrt(variance)

In [319]:
a = np.array([[1,2,3,4],
              [4,3,2,1]])
print(a.shape)
standard_deviation(a[:,0])

(2, 4)


2.1213203435596424

4. Tính xác suất phân phối Gaussian, dựa trên độ lệch chuẩn và phương sai

In [320]:
def summarize(dataset):
    dataset=np.array(dataset)
    temp=np.zeros((dataset.shape[1],2))
    print(temp.shape)
    for i in range(dataset.shape[1]):
        temp[i,0]=mean(dataset[:,i])
        temp[i,1]=standard_deviation(dataset[:,i])
    return temp

In [321]:
summarize(a)

(4, 2)


array([[2.5       , 2.12132034],
       [2.5       , 0.70710678],
       [2.5       , 0.70710678],
       [2.5       , 2.12132034]])

In [322]:
import math
def calculate_prob(x, mean, stdev):
    exponent = np.exp(-(x - mean)**2 / (2 * stdev*stdev))
    return (1 / (np.sqrt(2 * np.pi) * stdev*stdev)) * exponent

In [323]:
def get_accuracy(value, y_test):
    correct = 0
    for i in range(len(value)):
        if value[i] == y_test[i]:
            correct += 1
    return (correct / float(len(value))) * 100.0

5. Viết hàm chính để dự đoán. Tham khảo hàm bến dưới.

#Ham tinh va trả về label
def calculate_label(dataset,x):
    #x=np.array(x)
    column_label=dataset[:,-1]
    lebel=np.unique(dataset[:,-1],return_counts=True)
    value=np.zeros((len(np.unique(dataset[:,-1])),len(x)))
    for i in range(len(label)):
        sub_data=dataset[dataset[:,-1]==label[i]]
        for j in range(len(x)):
            s=1
            #pro=[calculate_prob(x[j,k],mean(sub_data[:,k]),standard_deviation(sub_data[:,k])) for k in range(x.shape[1])]
            for k in range(x.shape[1]):
                s*=calculate_prob(x[j,k],mean(sub_data[:,k]),standard_deviation(sub_data[:,k]))
            value[i][j]=s
    return np.argmax(value,axis=0)

In [324]:
def calculate_label(trainingSet,x):
    value_class = len(np.unique(trainingSet[:,-1]))
    value=np.zeros((len(np.unique(trainingSet[:,-1])),len(x)))
    print("v1",value.shape)
    for i in range(1,value_class+1):
        sub_data=trainingSet[trainingSet[:,-1]==i]
        
        d = x.shape[0]
        for j in range(d):
            s=1
            pro = []
            pro=[calculate_prob(x[j,k],mean(sub_data[:,k]),standard_deviation(sub_data[:,k])) for k in range(x.shape[1] - 1)]
            print(pro)
            for t in pro:
                s*=t
            value[i-1][j] = s
    # print(value)
    return np.argmax(value,axis=0) + 1

In [325]:
def main():
    test_number = 20
    dataset = pd.read_csv("Data_IRIS.csv", header=None).values
    trainingSet, testSet, y_test = train_test_split(dataset, test_number)
    testSet1 = np.array(testSet)
    N, d = testSet1.shape
    testSet = np.array(testSet)
    print(y_test)
    label = calculate_label(trainingSet, testSet)
    print(label)
    percen = get_accuracy(label, y_test)
    print("Phan tram doan dung")
    print(percen)

main()

[3. 2. 3. 1. 3. 1. 2. 3. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 3. 3.]
v1 (3, 20)
[0.0012896323423375721, 2.316993159646905, 1.1566111866243628e-105, 1.1667418713238356e-81]
[0.46224526030007046, 0.25551372129331273, 1.646416259369901e-29, 2.7523625291072653e-10]
[0.02599758293760886, 1.4677509504893511, 1.042738299567944e-84, 2.1819117001290144e-46]
[1.202598955385236, 0.34899544266608706, 12.411193340380253, 32.65694182670899]
[6.971635406582399e-08, 1.4677509504893511, 2.0449525298599926e-141, 2.2327574525890444e-66]
[2.7595712770339267, 0.5768199506812001, 12.91497679151177, 13.75867251823599]
[0.2539907737355316, 0.4390969651267189, 2.1163780395261784e-42, 5.764108380186036e-17]
[5.58183270746748e-12, 1.4677509504893511, 1.115307523731937e-189, 2.2327574525890444e-66]
[2.706778762187785, 1.4677509504893511, 12.411193340380253, 13.75867251823599]
[0.00011642691382906529, 1.4677509504893511, 9.373322454438273e-62, 3.293034097561195e-25]
[1.7269622732968793e-06, 1.9094170012377225, 6.74035608

6. Đọc file Data_IRIS.csv sử dụng hàm trên để dự đoán. In kết quả dự đoán.

In [326]:
if __name__ == "__main__":
    main()

[3. 2. 1. 3. 1. 3. 1. 1. 3. 3. 3. 3. 3. 1. 3. 1. 3. 3. 2. 1.]
v1 (3, 20)
[0.2539907737355316, 0.4390969651267189, 6.740356084595295e-95, 1.1655902329111318e-52]
[0.7761996224317163, 1.052396771365409, 1.621078922207954e-32, 6.834149647646255e-21]
[3.0986658791426134, 1.7153594311845852, 9.64657127177593, 32.65694182670899]
[3.1003931766329506e-05, 2.6225529758864043, 6.370706298774682e-129, 1.663204334658657e-98]
[2.706778762187785, 1.9094170012377225, 9.64657127177593, 32.65694182670899]
[0.06023490002859084, 1.4677509504893511, 7.887156444370742e-80, 2.1819117001290144e-46]
[0.7324987031783452, 2.316993159646905, 8.561161905137848, 32.65694182670899]
[3.2103643101796036, 2.7267791267025348, 8.561161905137848, 31.501692544935242]
[1.7269622732968793e-06, 2.316993159646905, 6.370706298774682e-129, 1.1667418713238356e-81]
[0.0012896323423375721, 0.7038533717943463, 6.838150384108313e-123, 2.2327574525890444e-66]
[0.7761996224317163, 0.7038533717943463, 1.042738299567944e-84, 2.530544769

In [327]:
data = pd.read_csv("Data_IRIS.csv",header=None).values
data

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3