In [289]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

Hàm đọc file từ s (địa chỉ file)

In [290]:
def HoangTrongHien_docfile(s):
    data = pd.read_csv(s).values
    return data

In [291]:
data = HoangTrongHien_docfile(s="data_classification.csv")
X = data[:,:-1]
y = data[:,-1]
X, y

(array([[8.62543976, 0.05892653],
        [3.82819154, 0.72319923],
        [7.15095484, 3.89942042],
        [6.47790044, 8.19818055],
        [1.9222695 , 1.33142726],
        [8.97821589, 0.99343751],
        [6.63560308, 8.54280268],
        [7.67235895, 5.41639979],
        [4.86601533, 2.04267129],
        [6.86140497, 9.65530972],
        [8.54042132, 2.59037423],
        [3.71788065, 5.38166211],
        [9.18129712, 0.17147465],
        [9.56014002, 0.02494649],
        [5.97136947, 4.18830187],
        [9.43820269, 1.94381244],
        [4.35755102, 9.88798331],
        [4.54033196, 6.71387336],
        [1.54910163, 9.37513216],
        [8.08197371, 9.84220681],
        [9.620465  , 2.09932754],
        [8.83477098, 3.15220412],
        [1.75344854, 4.2192426 ],
        [1.04321284, 2.60976512],
        [1.19638318, 7.47574486],
        [8.91006988, 8.23292794],
        [4.52961874, 4.90551154],
        [1.85911241, 5.69186756],
        [9.55717884, 1.64467191],
        [7.154

Hàm tách dữ liệu với train,test là dữ liệu kèm nhãn

In [292]:
def HoangTrongHien_tachdulieu(X,y):
    x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
    train = np.hstack((x_train,y_train.reshape(len(x_train),1)))
    test = np.hstack((x_test,y_test.reshape(len(x_test),1)))
    return train, test

In [293]:
data_train, data_test = HoangTrongHien_tachdulieu(X= X,y=y)
data_train.shape, data_test.shape

((79, 3), (20, 3))

Thêm cột 0 vào cuối tập train -> data_train

In [294]:
data_train = np.hstack((data_train,np.zeros((data_train.shape[0],1))))
data_train

array([[8.18297806, 0.97498656, 1.        , 0.        ],
       [7.06536045, 1.12132813, 0.        , 0.        ],
       [9.43820269, 1.94381244, 1.        , 0.        ],
       [7.25343893, 1.76251062, 1.        , 0.        ],
       [5.09102909, 9.87313409, 1.        , 0.        ],
       [2.92268449, 8.21759492, 1.        , 0.        ],
       [8.85164631, 1.02791596, 1.        , 0.        ],
       [9.68310414, 9.50704973, 1.        , 0.        ],
       [3.86304627, 3.91320229, 0.        , 0.        ],
       [7.09227303, 2.35745691, 0.        , 0.        ],
       [5.97136947, 4.18830187, 1.        , 0.        ],
       [0.92562818, 3.42126711, 0.        , 0.        ],
       [5.70052911, 7.08354423, 1.        , 0.        ],
       [0.66547833, 9.78263644, 1.        , 0.        ],
       [6.94443908, 6.48470389, 1.        , 0.        ],
       [9.94784093, 1.02645781, 1.        , 0.        ],
       [9.55717884, 1.64467191, 1.        , 0.        ],
       [8.83477098, 3.15220412,

Hàm tính khoảng cách theo công thức `a**2 - 2a*b + b**2`

In [295]:
def dist_cal(data,test):
        # print(data.shape)
        # print(test.shape)
        M_new = np.sum(data*data, 1) 
        P_new = np.sum(test*test, 1) 
        return np.sqrt(P_new.reshape(-1,1) + M_new.reshape(1,-1) - 2*test.dot(data.T))

`kc` với mỗi dòng lần lượt là khoảng các từ điểm test tới toàn bộ khoảng cách của dữ liệu train

In [296]:
kc = dist_cal(data_train[:,:-2], data_test[:,:-1])
kc.shape

(20, 79)

Hàm `HoangTrongHien_count` tính số lần nhãn xuất hiện nhiều nhất trong tập k 

In [297]:
def HoangTrongHien_count(arr):
    a,b = np.unique(arr, return_counts=True)
    return a[np.argmax(b)]

`rs` là kết quả sau khi lọc ra 

In [298]:
list_kc = []
rs = []
for i in kc:
    d = np.copy(data_train)
    d[:,-1] = i
    d = d[d[:,-1].argsort()]
    rs.append(HoangTrongHien_count(d[:,-2][:5]))
    
rs = np.array(rs)
rs,data_test[:,-1]


(array([1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
        1., 1., 1.]),
 array([1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
        0., 0., 1.]))

Hàm đánh giá độ chính xác

In [299]:
def HoangTrongHien_danhgia(y_pred, y_true):
    x = (y_pred == y_true)
    return np.sum(x)/len(x) * 100

# Kết quả

In [300]:
print(HoangTrongHien_danhgia(rs,data_test[:,-1]),"%")

90.0 %


Hàm đánh giá

In [301]:
def HoangTrongHien_HienKetQua(y_pred, y_true):
    c = np.unique(y_pred)
    m = np.zeros((len(c), len(c)))
    for i in range(len(c)):
        for j in range(len(c)):
            m[i,j] = np.sum((y_pred==c[i]) & (y_true==c[j]))

    return m


In [302]:
m = HoangTrongHien_HienKetQua(rs,data_test[:,-1])

Ma trận đánh giá

In [303]:
confusion = pd.DataFrame(data ={"Lớp": np.unique(rs),
                                "0": m[:,0],
                                "1": m[:,1]})
confusion

Lớp    0     1
0  0.0  8.0   0.0
1  1.0  2.0  10.0