Cho ma trận M và một điểm P

M=np.array([[200, 10, 1],
            [2000, 10, 1],
           [10, 2000, 0],
           [300, 10, 1],
           [400, 2000, 0],
           [20, 2000, 0],
            [10, 1000, 0],
            [300, 10, 1],
            [5, 300, 0],
            [2, 200, 0]])
P=np.array([200,10])

In [1]:
import numpy as np
M=np.array([[200, 10, 1],
            [2000, 10, 1],
           [10, 2000, 0],
           [300, 10, 1],
           [400, 2000, 0],
           [20, 2000, 0],
            [10, 1000, 0],
            [300, 10, 1],
            [5, 300, 0],
            [2, 200, 0]])
P=np.array([200,10])

In [2]:
from sklearn.model_selection import train_test_split
N,d=M.shape
X=M[:,0:d-1]
y=M[:,d-1]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
X_train

array([[   5,  300],
       [ 400, 2000],
       [  10, 2000],
       [   2,  200],
       [ 300,   10],
       [  10, 1000],
       [  20, 2000]])

In [3]:
print("X_train:",X_train)
print("X_test:",X_test)
print("y_train:",y_train)
print("y_test:",y_test)

X_train: [[   5  300]
 [ 400 2000]
 [  10 2000]
 [   2  200]
 [ 300   10]
 [  10 1000]
 [  20 2000]]
X_test: [[ 300   10]
 [2000   10]
 [ 200   10]]
y_train: [0 0 0 0 1 0 0]
y_test: [1 1 1]


In [4]:
XX=np.hstack((X_train,y_train.reshape(-1,1)))

In [5]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(7, 2) (7,)
(3, 2) (3,)


1. Viết hàm thêm cột số 0 vào trước ma trận M.

---



In [6]:
M = np.hstack((np.zeros((M.shape[0],1)),M))
M

array([[0.e+00, 2.e+02, 1.e+01, 1.e+00],
       [0.e+00, 2.e+03, 1.e+01, 1.e+00],
       [0.e+00, 1.e+01, 2.e+03, 0.e+00],
       [0.e+00, 3.e+02, 1.e+01, 1.e+00],
       [0.e+00, 4.e+02, 2.e+03, 0.e+00],
       [0.e+00, 2.e+01, 2.e+03, 0.e+00],
       [0.e+00, 1.e+01, 1.e+03, 0.e+00],
       [0.e+00, 3.e+02, 1.e+01, 1.e+00],
       [0.e+00, 5.e+00, 3.e+02, 0.e+00],
       [0.e+00, 2.e+00, 2.e+02, 0.e+00]])

2. Viết hàm tính khoảng cách từ điểm P đếm M lưu kết quả tính được vào cột số 0 vừa thêm vào

In [7]:
def dist_ps_fast(P, M):
    M_new = np.sum(M*M,1) 
    z_new = np.sum(P*P) 
    
    return np.sqrt(M_new + z_new - 2*M.dot(P))

In [8]:
import math
np.sqrt(np.sum(P - M[:,1:-1],1)** 2)

print(M)

[[0.e+00 2.e+02 1.e+01 1.e+00]
 [0.e+00 2.e+03 1.e+01 1.e+00]
 [0.e+00 1.e+01 2.e+03 0.e+00]
 [0.e+00 3.e+02 1.e+01 1.e+00]
 [0.e+00 4.e+02 2.e+03 0.e+00]
 [0.e+00 2.e+01 2.e+03 0.e+00]
 [0.e+00 1.e+01 1.e+03 0.e+00]
 [0.e+00 3.e+02 1.e+01 1.e+00]
 [0.e+00 5.e+00 3.e+02 0.e+00]
 [0.e+00 2.e+00 2.e+02 0.e+00]]


In [9]:
print(M[:,1:-1].shape)
print(P.shape)
M[:,0] += dist_ps_fast(P,M[:,1:-1])
M

(10, 2)
(2,)


array([[0.00000000e+00, 2.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [1.80000000e+03, 2.00000000e+03, 1.00000000e+01, 1.00000000e+00],
       [1.99904977e+03, 1.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [2.00002500e+03, 4.00000000e+02, 2.00000000e+03, 0.00000000e+00],
       [1.99812412e+03, 2.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [1.00806746e+03, 1.00000000e+01, 1.00000000e+03, 0.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [3.49463875e+02, 5.00000000e+00, 3.00000000e+02, 0.00000000e+00],
       [2.74415743e+02, 2.00000000e+00, 2.00000000e+02, 0.00000000e+00]])

3. Viết hàm sắp xếp M theo thứ tự tăng dần của cột đầu tiên (cột vừa tính được từ câu 2).

In [10]:
def sap_xep(M, col=0):
    for i in range(len(M) - 1):
        for j in range(i+1,len(M)):
            #print(M[i][col] , M[j][col])
            if M[i][col] > M[j][col]:
                M[[i, j]] = M[[j,i]]
    return M

In [11]:
mm = sap_xep(M)
mm

array([[0.00000000e+00, 2.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [2.74415743e+02, 2.00000000e+00, 2.00000000e+02, 0.00000000e+00],
       [3.49463875e+02, 5.00000000e+00, 3.00000000e+02, 0.00000000e+00],
       [1.00806746e+03, 1.00000000e+01, 1.00000000e+03, 0.00000000e+00],
       [1.80000000e+03, 2.00000000e+03, 1.00000000e+01, 1.00000000e+00],
       [1.99812412e+03, 2.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [1.99904977e+03, 1.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [2.00002500e+03, 4.00000000e+02, 2.00000000e+03, 0.00000000e+00]])

4. Lấy ra 3 giá trị theo thứ tự từ trên xuống của cột cuối cùng (cột nhãn) lưu vào L

In [12]:
L = mm[:10,-1]
L

array([1., 1., 1., 0., 0., 0., 1., 0., 0., 0.])

5. Viết hàm tìm giá trị xuất hiện nhiều nhất trong L. VD: L=[0,0,1,1,1,2,2,2,1,0,0,0,0] thì nhãn 0 xuất hiện nhiều nhất.

In [13]:
list1 = M[:3,M.shape[1]-1].tolist()
def counter_words_in_list(llist):
    d = {}
    for i in llist:
        if d.get(i):
            d[i] += 1
        else:
            d[i] = 1
    m = 0
    word = ""
    for i in d.keys():
        if m < d[i]:
            m = d[i]
            word = i
    return [word, m]


counter_words_in_list(L)

[0.0, 6]

6. Viết câu lệnh để load dữ liệu từ file Data_classification.csv.

In [14]:
import pandas as pd
data = pd.read_csv("data_classification.csv").values

In [15]:
data[:10]

array([[8.62543976, 0.05892653, 0.        ],
       [3.82819154, 0.72319923, 0.        ],
       [7.15095484, 3.89942042, 1.        ],
       [6.47790044, 8.19818055, 1.        ],
       [1.9222695 , 1.33142726, 0.        ],
       [8.97821589, 0.99343751, 1.        ],
       [6.63560308, 8.54280268, 1.        ],
       [7.67235895, 5.41639979, 1.        ],
       [4.86601533, 2.04267129, 0.        ],
       [6.86140497, 9.65530972, 1.        ]])

7. Tách dữ liệu thành hai tập train (X_train) và test. Tách tập test thành X_test và y_test.

In [16]:
X_train,X_test,y_train,y_test=train_test_split(data[:,:-1],data[:,-1],test_size=0.5)
XX=np.hstack((X_train,y_train.reshape(-1,1)))
print(XX.shape)

(49, 3)


8. Ghép cột số 0 vào đầu X_train

In [17]:
XX = np.hstack((np.zeros((XX.shape[0], 1)),XX))

XX[:10]


array([[0.        , 5.27238317, 9.14961537, 1.        ],
       [0.        , 8.85164631, 1.02791596, 1.        ],
       [0.        , 8.92270641, 7.75421671, 1.        ],
       [0.        , 5.09102909, 9.87313409, 1.        ],
       [0.        , 3.82819154, 0.72319923, 0.        ],
       [0.        , 2.99191148, 5.29921046, 0.        ],
       [0.        , 1.04321284, 2.60976512, 0.        ],
       [0.        , 2.92268449, 8.21759492, 1.        ],
       [0.        , 4.54033196, 6.71387336, 1.        ],
       [0.        , 6.77931871, 2.02818075, 0.        ]])

9. Duyệt qua từng điểm dữ liệu của X_test:

-    9.1 Tính khoảng cách đến tất cả các điểm của X_train
-    9.2 Sắp xếp X_train theo thứ tự tăng dần của cột đầu tiên.
-  9.3 Lấy ra k theo thứ tự từ trên xuống của cột nhãn. (k là một số lẻ: 3, 7, 9)
-  9.4 Xác nhãn xuất hiện nhiều nhất
Lưu tất cả nhãn tìm được vào Lable.

In [18]:
for i in range(len(X_test)):
    print(XX[:,1:-1].dot(X_test[i]))

[65.63395712 37.80923395 72.03867443 68.61941209 17.75900702 37.78601419
 17.02345947 52.26865264 50.63593806 35.22401433 25.5266105   6.40102984
 48.37265437 27.36621243 65.27157253 39.79792824 35.35507063 32.08230057
 20.66090761 35.62952125 44.55273044 38.10152758 40.72434255 51.85425877
 35.07790155 36.7943613  43.15525974 45.22648645 56.77808663 34.36562368
 15.67916028 41.64447401 40.1584797  48.47462954 20.68821704 46.82264366
 32.7366291  35.59455718 58.17921489 74.04323721 28.24667295 68.36185898
 43.5237156  27.7684814  59.9007312  67.59303608 39.058279   33.17156199
 35.92620093]
[22.31698873 18.38384507 27.47602194 22.93168987  8.32170302 12.80677347
  5.48004865 16.55931718 17.6667757  15.73205275  7.16333189  3.04124652
 16.02691095  9.14575203 23.36755155 11.53043603 18.41038002 16.65887617
  6.52394049 16.28971913 19.86588631 18.58124036 19.37106247 14.30409758
 17.02801285  9.79408276 17.05500072 17.57217959 20.38917717 16.42267353
  4.56391652 20.02845189 18.52416374 

In [19]:
tmp1 = XX[:,1:-1]
m = X_test[0]

dist_ps_fast(m,tmp1)

array([4.39623993, 6.54760565, 5.89462226, 5.02393111, 4.32913474,
       0.73654017, 3.59633175, 3.25806685, 1.87087886, 4.3250439 ,
       3.24590035, 5.32528827, 2.03083854, 1.99368299, 4.20851131,
       3.29624117, 7.73098392, 7.02270861, 3.11475808, 4.8519204 ,
       5.4428603 , 6.66885129, 6.49419722, 5.61388222, 6.06937227,
       4.18944352, 2.44335026, 2.29646195, 2.86318211, 5.62574695,
       3.95305163, 6.9337142 , 5.64906765, 5.48832069, 3.20418103,
       3.73345501, 4.88858366, 1.93543147, 3.93107397, 5.59452978,
       3.23088523, 5.00647566, 6.78811726, 2.10261294, 3.43657035,
       4.5723066 , 4.74683192, 3.18074439, 4.08302404])

In [20]:
ds = []
k = 5

for i in X_test:
    # i = np.array(i)
    xx = np.copy(XX)
    xx[:,0] += dist_ps_fast(i,xx[:,1:-1])
    ds.append(sap_xep(xx))
    
rs = []  
for i in ds:
    
    rs.append(counter_words_in_list(i[:k,-1])[0])




In [21]:
count = 0
for i in range(len(rs)):
    if rs[i] == y_test[i]:
        count += 1

my_accy = count/len(rs) * 100
print(my_accy,"%")

94.0 %


10. So sánh y_test và Lable để đánh giá tỉ lệ phần trăm đoán đúng.

11. Sử dụng thư viện về KNN để train và test

In [22]:
from sklearn import neighbors
from sklearn.metrics import accuracy_score
model = neighbors.KNeighborsClassifier(n_neighbors=5, p=2)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
sklearn_accy = 100*accuracy_score(y_true=y_test, y_pred=y_pred)
print("Độ chính xác {}KNN from sklearn: {}%".format(k,sklearn_accy))

Độ chính xác 5KNN from sklearn: 94.0%


12. Tổ chức các hàm đã viết thành lớp lấy tên là KNN_Ten_Ban

In [23]:
class KNN_Hien():
    def __init__(self,x_train,y_train) -> None:
        self.pre_process(x_train=x_train,y_train=y_train)
        
        
    def pre_process(self,x_train,y_train):
        self.XX = np.hstack((x_train,y_train.reshape(-1,1)))
        self.XX = np.hstack((np.zeros((self.XX.shape[0],1)), self.XX))
        #print(self.XX)
    
    def fit(self, test_data):
        self.ds = []
        if test_data.shape[0] > 1:
            tmp = self.dist_cal(test_data,self.XX[:,1:-1])
            for i,j in zip(tmp,range(len(tmp))):
                xx = np.copy(self.XX)
                xx[:,0] += i
                self.ds.append(self.sap_xep(xx))
                #print(self.sap_xep(xx))
            #print(self.ds[8])
                       
        else:
            xx = np.copy(self.XX)
            xx[:,0] += self.dist_1point_fast(i,xx[:,1:-1])
            self.ds.append(self.sap_xep(xx))

    
            
        
    def sap_xep(self,M, col=0):
        for i in range(len(M) - 1):
            for j in range(i+1,len(M)):
                #print(M[i][col] , M[j][col])
                if M[i][col] > M[j][col]:
                    M[[i, j]] = M[[j,i]]
        return M
    
    
    def dist_1point_fast(self,P, M):
        M_new = np.sum(M*M,1) 
        z_new = np.sum(P*P) 
        return np.sqrt(M_new + z_new - 2*M.dot(P))
    
    def dist_Npoint_fast(self,P,M):
        M_new = np.sum(M*M, 1) 
        P_new = np.sum(P*P, 1) 
        return np.sqrt(P_new.reshape(-1,1) + M_new.reshape(1,-1) - 2*P.dot(M.T))

    def dist_cal(self, P,M):
        try:
            rs = self.dist_1point_fast(P,M)
        except:
            rs = self.dist_Npoint_fast(P,M)
            
        return rs
            
    # list1 = M[:3,M.shape[1]-1].tolist()
    def counter_words_in_list(self,llist):
        d = {}
        for i in llist:
            if d.get(i):
                d[i] += 1
            else:
                d[i] = 1
        m = 0
        word = ""
        for i in d.keys():
            if m < d[i]:
                m = d[i]
                word = i
        return [word, m]

    def predict(self,k=5):
        rs = []  
        for i in self.ds:
            rs.append(self.counter_words_in_list(i[:k,-1])[0])
        return rs


In [24]:
#x_train,x_test,y_train,y_test = train_test_split(data[:,:-1], data[:,-1],test_size=0.5)
model = KNN_Hien(X_train,y_train)
k=5

model.fit(X_test)
y_pred = model.predict(k=5)
my_class_accy = 100*accuracy_score(y_true=y_test, y_pred=y_pred)
print("Độ chính xác của {}KNN : {}%".format(k,my_class_accy))

Độ chính xác của 5KNN : 94.0%


# Độ chính xác của ba phiên bản

In [25]:
print("Độ chính xác model bth:",my_accy,"%")
print("Độ chính xác model được viết bằng class:",my_class_accy,"%")
print("Độ chính xác model sklearn:",sklearn_accy,"%")

Độ chính xác model bth: 94.0
Độ chính xác model được viết bằng class: 94.0
Độ chính xác model sklearn: 94.0
